version: '3.8'

services:
  django:
    build:
      context: .
      dockerfile: ./django/Dockerfile
    command: >
      bash -c "gunicorn config.wsgi:application --bind 0.0.0.0:8000
      --error-logfile /var/log/gunicorn/error.log --access-logfile /var/log/gunicorn/access.log"
    expose:
      - 8000
    env_file:
      - ./.env.prod
    networks:
      backnet:
        ipv4_address: 172.16.238.11
  db:
    image: postgres:13.0-alpine
    volumes:
      - postgres_proj_changeme:/var/lib/postgresql/data/
    env_file:
      - ./.env.prod.db
    networks:
      backnet:
        ipv4_address: 172.16.238.13
  nginx:
    build: 
      context: .
      dockerfile: ./nginx/Dockerfile
    ports:
      - 80:80
    depends_on:
      - django
    networks:
      backnet:
        ipv4_address: 172.16.238.12

volumes:
  postgres_proj_changeme:
    external: true

networks:
  backnet:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.16.238.0/24
          gateway: 172.16.238.1
